### ISSUE TITLE
Fail rake data:migrate

### ISSUE THREAD

**Issue by inyerade** [OffgridElectric/rails-data-migrations#2]
`rake data:migrate`
the first try with this, give me:

```
Running via Spring preloader in process 1524
rake aborted!
NoMethodError: undefined method `data_source_exists?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00000006521768>
/var/lib/gems/2.3.0/gems/rails-data-migrations-1.0.2/lib/rails_data_migrations/migrator.rb:16:in `get_all_versions'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:854:in `current_version'
/var/lib/gems/2.3.0/gems/rails-data-migrations-1.0.2/lib/tasks/data_migrations.rake:19:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => data:migrate
(See full trace by running task with --trace)

```

I use Rails 4.2.5 and ruby ruby 2.3.1p112

**Comment by serggl** [comment]
thanks for the report!
This issue should be fixed now
